name: Qodana Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2024.2
        with:
          linter: jetbrains/qodana-jvm
          args: --fail-threshold 0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_131390707 }}
